import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
    return (
        <div className="font-bold">
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            Hello
        </div>
    )
}
